In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('concrete_data.csv')
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [3]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
# X_train, Y_train
# X_test, Y_test

In [5]:
df_columns = df.columns
predictors = df[df_columns[df_columns!='Strength']]
target = df['Strength']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
# Normalizing data

predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=42)

In [9]:
X_train

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
196,-0.827393,-0.856472,0.723653,-0.747734,0.216835,0.430603,1.650364,-0.279597
631,0.419421,-0.856472,-0.846733,0.113922,-1.038638,1.158540,0.117485,-0.612034
81,0.360094,1.606458,-0.846733,-1.211343,1.355131,-1.553862,1.332313,-0.675355
526,0.744760,-0.636257,1.356496,-1.290952,0.785983,-0.397651,0.341992,-0.675355
830,-1.140293,1.345678,1.465876,-0.120224,2.141895,-1.735203,-0.406362,-0.279597
...,...,...,...,...,...,...,...,...
87,0.049108,1.472011,-0.846733,-1.726464,0.836202,0.407453,0.375668,-0.675355
330,-0.328859,-0.856472,1.108046,-1.792024,0.970119,1.464634,0.340744,-0.501222
466,-0.869496,-0.856472,1.109609,-0.700905,0.618587,1.364317,0.315799,0.860186
121,1.854740,0.520451,-0.846733,-0.021882,0.451190,-1.553862,0.098777,-0.279597
860,0.314164,-0.856472,0.918975,-0.541686,0.635327,-0.616289,0.117485,-0.279597

In [10]:
Y_train

196    25.72
631    17.54
81     25.20
526    23.64
830    33.76
       ...
87     24.40
330    42.22
466    33.56
121    68.30
860    38.46
Name: Strength, Length: 721, dtype: float64

In [11]:
n_cols = predictors_norm.shape[1] # number of predictors
n_cols

8

In [12]:
import keras

Using TensorFlow backend.

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [15]:
# build the model
model = regression_model()

In [16]:
# fit the model
epochs = 50
model.fit(X_train, Y_train, epochs=epochs, verbose=1)

Epoch 1/50
721/721 [==============================] - 0s 196us/step - loss: 1633.9326
Epoch 2/50
721/721 [==============================] - 0s 52us/step - loss: 1618.7126
Epoch 3/50
721/721 [==============================] - 0s 50us/step - loss: 1603.7276
Epoch 4/50
721/721 [==============================] - 0s 51us/step - loss: 1589.0589
Epoch 5/50
721/721 [==============================] - 0s 52us/step - loss: 1573.8899
Epoch 6/50
721/721 [==============================] - 0s 56us/step - loss: 1558.2699
Epoch 7/50
721/721 [==============================] - 0s 53us/step - loss: 1542.0323
Epoch 8/50
721/721 [==============================] - 0s 51us/step - loss: 1524.7947
Epoch 9/50
721/721 [==============================] - 0s 47us/step - loss: 1506.4897
Epoch 10/50
721/721 [==============================] - 0s 47us/step - loss: 1487.3756
Epoch 11/50
721/721 [==============================] - 0s 46us/step - loss: 1467.0362
Epoch 12/50
721/721 [==============================] - 0s 45us/step - loss: 1445.6978
Epoch 13/50
721/721 [==============================] - 0s 45us/step - loss: 1423.4971
Epoch 14/50
721/721 [==============================] - 0s 47us/step - loss: 1399.8030
Epoch 15/50
721/721 [==============================] - 0s 46us/step - loss: 1375.6584
Epoch 16/50
721/721 [==============================] - 0s 46us/step - loss: 1350.1429
Epoch 17/50
721/721 [==============================] - 0s 52us/step - loss: 1323.7778
Epoch 18/50
721/721 [==============================] - 0s 46us/step - loss: 1296.8279
Epoch 19/50
721/721 [==============================] - 0s 46us/step - loss: 1268.9656
Epoch 20/50
721/721 [==============================] - 0s 46us/step - loss: 1240.0527
Epoch 21/50
721/721 [==============================] - 0s 45us/step - loss: 1210.8865
Epoch 22/50
721/721 [==============================] - 0s 48us/step - loss: 1181.3072
Epoch 23/50
721/721 [==============================] - 0s 52us/step - loss: 1151.2877
Epoch 24/50
721/721 [==============================] - 0s 49us/step - loss: 1120.0998
Epoch 25/50
721/721 [==============================] - 0s 48us/step - loss: 1089.2410
Epoch 26/50
721/721 [==============================] - 0s 49us/step - loss: 1057.3739
Epoch 27/50
721/721 [==============================] - 0s 47us/step - loss: 1026.0152
Epoch 28/50
721/721 [==============================] - 0s 51us/step - loss: 994.1904
Epoch 29/50
721/721 [==============================] - 0s 51us/step - loss: 962.3023
Epoch 30/50
721/721 [==============================] - 0s 46us/step - loss: 930.3411
Epoch 31/50
721/721 [==============================] - 0s 47us/step - loss: 898.2138
Epoch 32/50
721/721 [==============================] - 0s 50us/step - loss: 866.0767
Epoch 33/50
721/721 [==============================] - 0s 48us/step - loss: 834.0968
Epoch 34/50
721/721 [==============================] - 0s 47us/step - loss: 802.2064
Epoch 35/50
721/721 [==============================] - 0s 46us/step - loss: 771.0571
Epoch 36/50
721/721 [==============================] - 0s 48us/step - loss: 740.3099
Epoch 37/50
721/721 [==============================] - 0s 46us/step - loss: 709.8676
Epoch 38/50
721/721 [==============================] - 0s 44us/step - loss: 680.5635
Epoch 39/50
721/721 [==============================] - 0s 46us/step - loss: 651.5621
Epoch 40/50
721/721 [==============================] - 0s 48us/step - loss: 623.5321
Epoch 41/50
721/721 [==============================] - 0s 48us/step - loss: 596.8270
Epoch 42/50
721/721 [==============================] - 0s 46us/step - loss: 570.7895
Epoch 43/50
721/721 [==============================] - 0s 50us/step - loss: 545.6950
Epoch 44/50
721/721 [==============================] - 0s 52us/step - loss: 521.8357
Epoch 45/50
721/721 [==============================] - 0s 57us/step - loss: 498.8052
Epoch 46/50
721/721 [==============================] - 0s 50us/step - loss: 477.0933
Epoch 47/50
721/721 [==============================] - 0s 47us/step - loss: 456.1205
Epoch 48/50
721/721 [==============================] - 0s 46us/step - loss: 436.6777
Epoch 49/50
721/721 [==============================] - 0s 47us/step - loss: 417.7952
Epoch 50/50
721/721 [==============================] - 0s 45us/step - loss: 400.1719

In [17]:
loss_val = model.evaluate(X_test, Y_test)
Y_pred = model.predict(X_test)
loss_val

309/309 [==============================] - 0s 81us/step

362.4659476172191

In [18]:
from sklearn.metrics import mean_squared_error

In [19]:
mean_square_error = mean_squared_error(Y_test, Y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

362.46594172354327 0.0

In [20]:
# Creating the list 
# C) Increate the number of epochs to 100 

total_mean_squared_errors = 50
# epochs = 50
epochs = 100
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')

print("Mean of 50 mean squared errors with normalized data: "+str(mean))
print("Standard Deviation of 50 mean squared errors with normalized data: "+str(standard_deviation))

MSE 1: 99.62041372157223
MSE 2: 75.1264253387945
MSE 3: 43.715213750944166
MSE 4: 42.000209555270985
MSE 5: 41.23048605810863
MSE 6: 42.333005936014615
MSE 7: 43.79234476922785
MSE 8: 33.10934281580656
MSE 9: 35.52432662075006
MSE 10: 33.41029925176627
MSE 11: 32.0340246614129
MSE 12: 28.545711937074138
MSE 13: 35.961409936059255
MSE 14: 37.2768879615759
MSE 15: 28.98752161291425
MSE 16: 28.23686267642913
MSE 17: 30.5059041760886
MSE 18: 29.410238704249313
MSE 19: 28.34503140495819
MSE 20: 29.48700752381754
MSE 21: 28.83987950198473
MSE 22: 27.65195795941893
MSE 23: 26.16223977838905
MSE 24: 27.166379589093157
MSE 25: 29.169590061150707
MSE 26: 31.89379812444298
MSE 27: 26.82084848348377
MSE 28: 26.677379848887618
MSE 29: 32.413628982494565
MSE 30: 31.65497564420731
MSE 31: 28.36071504512651
MSE 32: 25.455319784219984
MSE 33: 26.54016402161237
MSE 34: 28.03204379035431
MSE 35: 29.952713679341436
MSE 36: 33.40860415585219
MSE 37: 24.720115177068124
MSE 38: 31.738715927963504
MSE 39: 29.251681985206975
MSE 40: 25.882393574637504
MSE 41: 31.684540529467142
MSE 42: 23.2025014883492
MSE 43: 27.568384991494582
MSE 44: 31.240672361503528
MSE 45: 29.285700418416734
MSE 46: 28.585161196761145
MSE 47: 28.97424464549833
MSE 48: 28.494861318841334
MSE 49: 29.367862386610902
MSE 50: 30.715356339142932


Mean of 50 mean squared errors with normalized data: 33.19130192653798
Standard Deviation of 50 mean squared errors with normalized data: 12.29235953526509