In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.read_csv('concrete_data.csv')
df.describe()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
count,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000,1030.000000
mean,281.167864,73.895825,54.188350,181.567282,6.204660,972.918932,773.580485,45.662136,35.817961
std,104.506364,86.279342,63.997004,21.354219,5.973841,77.753954,80.175980,63.169912,16.705742
min,102.000000,0.000000,0.000000,121.800000,0.000000,801.000000,594.000000,1.000000,2.330000
25%,192.375000,0.000000,0.000000,164.900000,0.000000,932.000000,730.950000,7.000000,23.710000
50%,272.900000,22.000000,0.000000,185.000000,6.400000,968.000000,779.500000,28.000000,34.445000
75%,350.000000,142.950000,118.300000,192.000000,10.200000,1029.400000,824.000000,56.000000,46.135000
max,540.000000,359.400000,200.100000,247.000000,32.200000,1145.000000,992.600000,365.000000,82.600000

In [3]:
df.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age,Strength
0,540.0,0.0,0.0,162.0,2.5,1040.0,676.0,28,79.99
1,540.0,0.0,0.0,162.0,2.5,1055.0,676.0,28,61.89
2,332.5,142.5,0.0,228.0,0.0,932.0,594.0,270,40.27
3,332.5,142.5,0.0,228.0,0.0,932.0,594.0,365,41.05
4,198.6,132.4,0.0,192.0,0.0,978.4,825.5,360,44.30

In [4]:
# X_train, Y_train
# X_test, Y_test

In [5]:
df_columns = df.columns
predictors = df[df_columns[df_columns!='Strength']]
target = df['Strength']

In [6]:
from sklearn.model_selection import train_test_split

In [7]:
# Normalizing data

predictors_norm = (predictors - predictors.mean()) / predictors.std()
predictors_norm.head()

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
0,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,0.862735,-1.217079,-0.279597
1,2.476712,-0.856472,-0.846733,-0.916319,-0.620147,1.055651,-1.217079,-0.279597
2,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,3.551340
3,0.491187,0.795140,-0.846733,2.174405,-1.038638,-0.526262,-2.239829,5.055221
4,-0.790075,0.678079,-0.846733,0.488555,-1.038638,0.070492,0.647569,4.976069

In [8]:
X_train, X_test, Y_train, Y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=42)

In [9]:
X_train

,Cement,Blast Furnace Slag,Fly Ash,Water,Superplasticizer,Coarse Aggregate,Fine Aggregate,Age
196,-0.827393,-0.856472,0.723653,-0.747734,0.216835,0.430603,1.650364,-0.279597
631,0.419421,-0.856472,-0.846733,0.113922,-1.038638,1.158540,0.117485,-0.612034
81,0.360094,1.606458,-0.846733,-1.211343,1.355131,-1.553862,1.332313,-0.675355
526,0.744760,-0.636257,1.356496,-1.290952,0.785983,-0.397651,0.341992,-0.675355
830,-1.140293,1.345678,1.465876,-0.120224,2.141895,-1.735203,-0.406362,-0.279597
...,...,...,...,...,...,...,...,...
87,0.049108,1.472011,-0.846733,-1.726464,0.836202,0.407453,0.375668,-0.675355
330,-0.328859,-0.856472,1.108046,-1.792024,0.970119,1.464634,0.340744,-0.501222
466,-0.869496,-0.856472,1.109609,-0.700905,0.618587,1.364317,0.315799,0.860186
121,1.854740,0.520451,-0.846733,-0.021882,0.451190,-1.553862,0.098777,-0.279597
860,0.314164,-0.856472,0.918975,-0.541686,0.635327,-0.616289,0.117485,-0.279597

In [10]:
Y_train

196    25.72
631    17.54
81     25.20
526    23.64
830    33.76
       ...
87     24.40
330    42.22
466    33.56
121    68.30
860    38.46
Name: Strength, Length: 721, dtype: float64

In [11]:
n_cols = predictors.shape[1] # number of predictors
n_cols

8

In [12]:
import keras

Using TensorFlow backend.

In [13]:
from keras.models import Sequential
from keras.layers import Dense

In [14]:
# Increasing the number of hidden layers
def regression_model():
    # create model
    model = Sequential()
    model.add(Dense(10, activation='relu', input_shape=(n_cols,)))  # 1 hidden layer
    model.add(Dense(10, activation='relu'))  # 2 hidden layers
    model.add(Dense(10, activation='relu'))  # 3 hidden layers
    model.add(Dense(1))
    
    # compile model
    model.compile(optimizer='adam', loss='mean_squared_error')
    return model

In [15]:
# build the model
model = regression_model()

In [16]:
# fit the model
epochs = 50
model.fit(X_train, Y_train, epochs=epochs, verbose=1)

Epoch 1/50
721/721 [==============================] - 0s 294us/step - loss: 1636.9589
Epoch 2/50
721/721 [==============================] - 0s 63us/step - loss: 1607.4021
Epoch 3/50
721/721 [==============================] - 0s 65us/step - loss: 1584.8465
Epoch 4/50
721/721 [==============================] - 0s 65us/step - loss: 1561.3519
Epoch 5/50
721/721 [==============================] - 0s 63us/step - loss: 1529.8692
Epoch 6/50
721/721 [==============================] - 0s 63us/step - loss: 1481.6816
Epoch 7/50
721/721 [==============================] - 0s 62us/step - loss: 1404.6940
Epoch 8/50
721/721 [==============================] - 0s 68us/step - loss: 1288.4019
Epoch 9/50
721/721 [==============================] - 0s 67us/step - loss: 1130.1939
Epoch 10/50
721/721 [==============================] - 0s 66us/step - loss: 918.4827
Epoch 11/50
721/721 [==============================] - 0s 65us/step - loss: 675.1565
Epoch 12/50
721/721 [==============================] - 0s 64us/step - loss: 452.3215
Epoch 13/50
721/721 [==============================] - 0s 59us/step - loss: 307.4927
Epoch 14/50
721/721 [==============================] - 0s 63us/step - loss: 248.4885
Epoch 15/50
721/721 [==============================] - 0s 63us/step - loss: 221.0331
Epoch 16/50
721/721 [==============================] - 0s 67us/step - loss: 206.6716
Epoch 17/50
721/721 [==============================] - 0s 61us/step - loss: 194.9691
Epoch 18/50
721/721 [==============================] - 0s 55us/step - loss: 187.6182
Epoch 19/50
721/721 [==============================] - 0s 57us/step - loss: 181.5206
Epoch 20/50
721/721 [==============================] - 0s 57us/step - loss: 176.7924
Epoch 21/50
721/721 [==============================] - 0s 58us/step - loss: 173.0938
Epoch 22/50
721/721 [==============================] - 0s 53us/step - loss: 169.5002
Epoch 23/50
721/721 [==============================] - 0s 57us/step - loss: 166.6505
Epoch 24/50
721/721 [==============================] - 0s 57us/step - loss: 163.4791
Epoch 25/50
721/721 [==============================] - 0s 58us/step - loss: 160.4943
Epoch 26/50
721/721 [==============================] - 0s 56us/step - loss: 157.9624
Epoch 27/50
721/721 [==============================] - 0s 58us/step - loss: 155.4566
Epoch 28/50
721/721 [==============================] - 0s 55us/step - loss: 153.7906
Epoch 29/50
721/721 [==============================] - 0s 57us/step - loss: 151.3788
Epoch 30/50
721/721 [==============================] - 0s 58us/step - loss: 149.5252
Epoch 31/50
721/721 [==============================] - 0s 62us/step - loss: 147.6220
Epoch 32/50
721/721 [==============================] - 0s 56us/step - loss: 145.6751
Epoch 33/50
721/721 [==============================] - 0s 59us/step - loss: 144.2173
Epoch 34/50
721/721 [==============================] - 0s 57us/step - loss: 142.6770
Epoch 35/50
721/721 [==============================] - 0s 55us/step - loss: 141.2884
Epoch 36/50
721/721 [==============================] - 0s 55us/step - loss: 139.8159
Epoch 37/50
721/721 [==============================] - 0s 57us/step - loss: 138.6346
Epoch 38/50
721/721 [==============================] - 0s 57us/step - loss: 137.9204
Epoch 39/50
721/721 [==============================] - 0s 59us/step - loss: 136.8011
Epoch 40/50
721/721 [==============================] - 0s 56us/step - loss: 135.4920
Epoch 41/50
721/721 [==============================] - 0s 58us/step - loss: 135.0943
Epoch 42/50
721/721 [==============================] - 0s 56us/step - loss: 134.0821
Epoch 43/50
721/721 [==============================] - 0s 56us/step - loss: 133.6763
Epoch 44/50
721/721 [==============================] - 0s 53us/step - loss: 132.6178
Epoch 45/50
721/721 [==============================] - 0s 57us/step - loss: 132.0585
Epoch 46/50
721/721 [==============================] - 0s 53us/step - loss: 130.8476
Epoch 47/50
721/721 [==============================] - 0s 59us/step - loss: 130.4316
Epoch 48/50
721/721 [==============================] - 0s 62us/step - loss: 129.5413
Epoch 49/50
721/721 [==============================] - 0s 64us/step - loss: 128.6608
Epoch 50/50
721/721 [==============================] - 0s 60us/step - loss: 128.1007

In [17]:
loss_val = model.evaluate(X_test, Y_test)
Y_pred = model.predict(X_test)
loss_val

309/309 [==============================] - 0s 88us/step

127.91976790443593

In [18]:
from sklearn.metrics import mean_squared_error

In [19]:
mean_square_error = mean_squared_error(Y_test, Y_pred)
mean = np.mean(mean_square_error)
standard_deviation = np.std(mean_square_error)
print(mean, standard_deviation)

127.91976925918067 0.0

In [20]:
# Creating the list
# D) Increase the number of hidden layers 

total_mean_squared_errors = 50
epochs = 50
mean_squared_errors = []
for i in range(0, total_mean_squared_errors):
    X_train, X_test, y_train, y_test = train_test_split(predictors_norm, target, test_size=0.3, random_state=i)
    model.fit(X_train, y_train, epochs=epochs, verbose=0)
    MSE = model.evaluate(X_test, y_test, verbose=0)
    print("MSE "+str(i+1)+": "+str(MSE))
    y_pred = model.predict(X_test)
    mean_square_error = mean_squared_error(y_test, y_pred)
    mean_squared_errors.append(mean_square_error)

mean_squared_errors = np.array(mean_squared_errors)
mean = np.mean(mean_squared_errors)
standard_deviation = np.std(mean_squared_errors)

print('\n')

print("Mean of 50 mean squared errors without normalized data: "+str(mean))
print("Standard Deviation of 50 mean squared errors without normalized data: "+str(standard_deviation))

MSE 1: 89.90170605360112
MSE 2: 72.88230330581418
MSE 3: 54.379825184646165
MSE 4: 48.094705698945376
MSE 5: 40.57498733125458
MSE 6: 39.97783015229555
MSE 7: 42.14253027462265
MSE 8: 30.8062511493473
MSE 9: 31.77490619548316
MSE 10: 32.806369664213804
MSE 11: 30.84118161000866
MSE 12: 26.000327014614463
MSE 13: 34.34536638846289
MSE 14: 34.731655244302594
MSE 15: 28.87106116458436
MSE 16: 22.59211269242864
MSE 17: 25.429575818256268
MSE 18: 25.217620821832455
MSE 19: 24.17545992039554
MSE 20: 29.43888580297575
MSE 21: 24.715731315242433
MSE 22: 24.97425539825341
MSE 23: 20.06584454508661
MSE 24: 22.49740349976376
MSE 25: 22.926582373461677
MSE 26: 27.925001199963024
MSE 27: 23.125549168262665
MSE 28: 21.83270992661757
MSE 29: 26.291842747660517
MSE 30: 24.82574273081659
MSE 31: 20.73465346055509
MSE 32: 17.131476726346804
MSE 33: 17.96507234789407
MSE 34: 22.59358480755951
MSE 35: 22.81316365856183
MSE 36: 25.538577965548125
MSE 37: 16.321029326676552
MSE 38: 21.224007875016593
MSE 39: 19.949081556696722
MSE 40: 18.075437564294315
MSE 41: 23.936661686326307
MSE 42: 19.264911768891665
MSE 43: 21.583481251614764
MSE 44: 22.48012001383266
MSE 45: 23.02672180620212
MSE 46: 23.860020714670323
MSE 47: 22.941896531188373
MSE 48: 18.54160360688145
MSE 49: 22.354018270004914
MSE 50: 24.13523125262708


Mean of 50 mean squared errors without normalized data: 28.572721040878424
Standard Deviation of 50 mean squared errors without normalized data: 13.33895718011391